[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm install && CI= npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
