[build]
  base = "frontend"
  publish = "build"
  command = "rm -rf node_modules && npm install && npm run build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
